"""initial schema

Revision ID: 43c806e64582
Revises: 
Create Date: 2026-08-24 13:36:32.941016
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from crypto_trader.persistence.models import ExactDecimal


revision: str = '43c806e64582'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_projection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('total', ExactDecimal(length=80), nullable=False),
    sa.Column('available', ExactDecimal(length=80), nullable=False),
    sa.Column('frozen', ExactDecimal(length=80), nullable=False),
    sa.Column('equity', ExactDecimal(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'currency', name='uq_accounts_projection_account_currency')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_event_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_audit_events_event_id')
    )
    op.create_index(op.f('ix_audit_events_audit_event_id'), 'audit_events', ['audit_event_id'], unique=False)
    op.create_table('engine_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('ledger_transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('fill_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id', name='uq_ledger_transactions_transaction_id')
    )
    op.create_index(op.f('ix_ledger_transactions_entry_type'), 'ledger_transactions', ['entry_type'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('bids_json', sa.String(length=8000), nullable=False),
    sa.Column('asks_json', sa.String(length=8000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'sequence', name='uq_market_snapshots_symbol_sequence')
    )
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('internal_order_id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('price', ExactDecimal(length=80), nullable=True),
    sa.Column('quantity', ExactDecimal(length=80), nullable=False),
    sa.Column('filled_quantity', ExactDecimal(length=80), nullable=False),
    sa.Column('avg_fill_price', ExactDecimal(length=80), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('last_event_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('internal_order_id'),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id'),
    sa.UniqueConstraint('exchange_order_id')
    )
    op.create_index(op.f('ix_orders_run_id'), 'orders', ['run_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions_projection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('quantity', ExactDecimal(length=80), nullable=False),
    sa.Column('avg_entry_price', ExactDecimal(length=80), nullable=True),
    sa.Column('cost_basis', ExactDecimal(length=80), nullable=False),
    sa.Column('realized_pnl', ExactDecimal(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_positions_projection_account_symbol')
    )
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('compared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('local_balances_json', sa.JSON(), nullable=True),
    sa.Column('exchange_balances_json', sa.JSON(), nullable=True),
    sa.Column('positions_diff_json', sa.JSON(), nullable=True),
    sa.Column('alerts_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_run_id'), 'reconciliation_runs', ['run_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('risk_decision_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('checks_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('risk_decision_id')
    )
    op.create_index(op.f('ix_risk_decisions_client_order_id'), 'risk_decisions', ['client_order_id'], unique=False)
    op.create_table('runtime_leases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lease_key', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.Float(), nullable=False),
    sa.Column('renewed_at', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_key'),
    sa.UniqueConstraint('token')
    )
    op.create_table('fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fill_id', sa.String(length=64), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', ExactDecimal(length=80), nullable=False),
    sa.Column('quantity', ExactDecimal(length=80), nullable=False),
    sa.Column('fee', ExactDecimal(length=80), nullable=False),
    sa.Column('fee_currency', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.internal_order_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id', name='uq_fills_fill_id'),
    sa.UniqueConstraint('trade_id', name='uq_fills_trade_id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', ExactDecimal(length=80), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('fill_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', name='uq_ledger_entries_entry_id')
    )
    op.create_index('ix_ledger_entries_transaction_seq', 'ledger_entries', ['transaction_id', 'seq'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('status_after', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.internal_order_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_order_events_event_id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('fill_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', ExactDecimal(length=80), nullable=False),
    sa.Column('quantity', ExactDecimal(length=80), nullable=False),
    sa.Column('fee', ExactDecimal(length=80), nullable=False),
    sa.Column('fee_currency', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.internal_order_id'], ),
    sa.PrimaryKeyConstraint('trade_id'),
    sa.UniqueConstraint('fill_id')
    )
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_ledger_entries_transaction_seq', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_table('runtime_leases')
    op.drop_index(op.f('ix_risk_decisions_client_order_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_reconciliation_runs_run_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_table('positions_projection')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_run_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_ledger_transactions_entry_type'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_table('engine_runs')
    op.drop_index(op.f('ix_audit_events_audit_event_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts_projection')
    # ### end Alembic commands ###
