import { useEffect, useState } from "react";
import { API_BASE_URL, WS_URL } from "./api/client";
import { useTradingSnapshot } from "./hooks/useTradingSnapshot";
import type { ApiState, Order, TradingSnapshot } from "./types/api";

type Page = "overview" | "strategies" | "signals" | "positions" | "orders" | "risk" | "reviews" | "daily-review" | "learning" | "system";
const pages: Array<[Page, string]> = [["overview", "Overview"], ["strategies", "Strategies"], ["signals", "Signals"], ["positions", "Positions"], ["orders", "Orders"], ["risk", "Risk"], ["reviews", "Reviews"], ["daily-review", "Daily Review"], ["learning", "Learning"], ["system", "System"]];

function resolvePage(hash: string): Page { const page = hash.replace(/^#\/?/, "") as Page; return pages.some(([id]) => id === page) ? page : "overview"; }
function display(value: unknown) { if (value === undefined || value === null || value === "") return "No data"; if (typeof value === "boolean") return value ? "Yes" : "No"; return String(value); }
function State({ source }: { source: ApiState<unknown> }) { const label = source.status === "ready" ? "LIVE BACKEND" : source.status === "empty" ? "NO DATA" : source.status === "unavailable" ? "NOT AVAILABLE YET" : source.status === "offline" ? "BACKEND OFFLINE" : source.status === "error" ? "BACKEND ERROR" : "LOADING"; return <span className={`status ${source.status}`}>{label}</span>; }
function Panel({ title, source, children }: { title: string; source?: ApiState<unknown>; children: React.ReactNode }) { return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{source && <State source={source} />}</div>{children}</section>; }
function Fields({ values }: { values: Array<[string, unknown]> }) { return <dl className="field-grid">{values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{display(value)}</dd></div>)}</dl>; }
function Unavailable({ title, source }: { title: string; source: ApiState<unknown> }) { const message = source.status === "unavailable" ? "Backend endpoint unavailable" : source.status === "offline" ? "Backend Offline" : source.status === "empty" ? "No data" : source.message || "Loading backend data"; return <Panel title={title} source={source}><p className="empty-state">{message}</p></Panel>; }

function Overview({ snapshot }: { snapshot: TradingSnapshot }) {
  const account = snapshot.account.data; const runtime = snapshot.runtime.data; const positions = Object.values(snapshot.positions.data ?? {}); const orders = snapshot.orders.data ?? [];
  return <div className="panel-grid"><Panel title="Engine Status" source={snapshot.runtime}><Fields values={[["Runtime", runtime?.runtime_state ?? runtime?.engine], ["Trading Mode", account?.mode], ["Market Data Health", (snapshot.health.data as Record<string, unknown> | undefined)?.overall], ["Kill Switch", (snapshot.killswitch.data as Record<string, unknown> | undefined)?.enabled]]} /></Panel><Panel title="Portfolio" source={snapshot.account}><Fields values={[["NAV / Equity", account?.equity], ["Daily PnL", undefined], ["Drawdown", undefined], ["Margin Usage", account?.margin_used], ["Open Positions", positions.length], ["Open Orders", orders.filter((order) => !["FILLED", "CANCELLED", "REJECTED", "EXPIRED"].includes(order.status)).length]]} /></Panel><Panel title="Exposure & strategy state" source={snapshot.optional["/risk"] ?? snapshot.runtime}><Fields values={[["LONG Exposure", undefined], ["SHORT Exposure", undefined], ["Gross Exposure", undefined], ["Net Exposure", undefined], ["Effective Leverage", undefined], ["Current Regime", undefined], ["Strategy Status", runtime?.strategy_status]]} /></Panel></div>;
}

function Strategies({ snapshot }: { snapshot: TradingSnapshot }) { const state = snapshot.optional["/strategies"] ?? { status: "loading" as const }; return state.status === "ready" ? <Panel title="Strategy Status" source={state}><pre className="json-view">{JSON.stringify(state.data, null, 2)}</pre></Panel> : <Unavailable title="Strategy Status" source={state} />; }
function Signals({ snapshot }: { snapshot: TradingSnapshot }) { const state = snapshot.optional["/signals"] ?? { status: "loading" as const }; return <div className="panel-grid"><Unavailable title="Signal evidence" source={state} /><Panel title="WHY THIS TRADE?"><Fields values={[["Regime", undefined], ["Trend vote", undefined], ["Momentum vote", undefined], ["Breakout vote", undefined], ["Mean Reversion vote", undefined], ["Funding / Basis vote", undefined], ["Raw confidence", undefined], ["Calibrated confidence", undefined], ["Final Decision", undefined], ["Risk-capped leverage", undefined], ["Stress result", undefined]]} /><p className="empty-state">Unavailable until the Signals API supplies backend-owned decision evidence.</p></Panel></div>; }
function Positions({ snapshot }: { snapshot: TradingSnapshot }) { const rows = Object.values(snapshot.positions.data ?? {}); if (snapshot.positions.status !== "ready" || !rows.length) return <Unavailable title="Positions" source={snapshot.positions} />; return <Panel title="Positions" source={snapshot.positions}><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>LONG / SHORT</th><th>Entry</th><th>Quantity</th><th>Notional</th><th>Realized PnL</th><th>Updated</th></tr></thead><tbody>{rows.map((position) => <tr key={position.symbol}><td>{position.symbol}</td><td>{Number(position.quantity) >= 0 ? "LONG" : "SHORT"}</td><td>{display(position.avg_entry_price)}</td><td>{position.quantity}</td><td>{position.cost_basis}</td><td>{position.realized_pnl}</td><td>{display(position.updated_at)}</td></tr>)}</tbody></table></div><p className="empty-state">Mark price, leverage, margin, liquidation and funding PnL are unavailable until the backend exposes them.</p></Panel>; }
function Orders({ snapshot }: { snapshot: TradingSnapshot }) { const rows = snapshot.orders.data ?? []; if (snapshot.orders.status !== "ready" || !rows.length) return <Unavailable title="Orders" source={snapshot.orders} />; return <Panel title="Orders" source={snapshot.orders}><div className="table-wrap"><table><thead><tr><th>Order ID</th><th>Client Order ID</th><th>Symbol</th><th>Side</th><th>Type</th><th>Price</th><th>Quantity</th><th>Filled</th><th>Status</th><th>Updated</th></tr></thead><tbody>{rows.map((order: Order) => <tr key={order.internal_order_id} className={order.status === "UNKNOWN" ? "unknown" : ""}><td>{order.internal_order_id}</td><td>{order.client_order_id}</td><td>{order.symbol}</td><td>{order.side}</td><td>{order.order_type}</td><td>{display(order.price)}</td><td>{order.quantity}</td><td>{order.filled_quantity}</td><td>{order.status === "UNKNOWN" ? "UNKNOWN — Exchange reconciliation required" : order.status}</td><td>{order.updated_at}</td></tr>)}</tbody></table></div></Panel>; }
function Risk({ snapshot }: { snapshot: TradingSnapshot }) { const state = snapshot.optional["/risk"] ?? { status: "loading" as const }; return <div className="panel-grid"><Unavailable title="Risk" source={state} /><Panel title="Kill Switch" source={snapshot.killswitch}><Fields values={[["Backend State", (snapshot.killswitch.data as Record<string, unknown> | undefined)?.enabled], ["Current Drawdown", undefined], ["Risk Multiplier", undefined], ["Effective Leverage", undefined], ["Gross Exposure", undefined], ["Net Exposure", undefined], ["Risk Reject Count", undefined]]} /><p className="empty-state">GLOBAL KILL SWITCH is backend-owned; this UI does not trigger it.</p></Panel></div>; }
function Deferred({ title, message, source }: { title: string; message: string; source: ApiState<unknown> }) { return <Unavailable title={title} source={source.status === "unavailable" ? { ...source, message } : source} />; }
function System({ snapshot }: { snapshot: TradingSnapshot }) { return <div className="panel-grid"><Panel title="Connectivity"><Fields values={[["API URL", API_BASE_URL], ["WebSocket URL", WS_URL], ["WebSocket", snapshot.websocket], ["Last Event", snapshot.lastEvent?.event_type], ["Frontend", "Connected to local backend only"]]} /></Panel><Panel title="Backend services" source={snapshot.ready}><Fields values={[["Ready", (snapshot.ready.data as Record<string, unknown> | undefined)?.ready], ["Runtime", (snapshot.runtime.data as Record<string, unknown> | undefined)?.runtime_state ?? (snapshot.runtime.data as Record<string, unknown> | undefined)?.engine], ["Database", (snapshot.runtime.data as Record<string, unknown> | undefined)?.database], ["Last backend event", snapshot.lastEvent?.payload?.state]]} /></Panel></div>; }
function Content({ page, snapshot }: { page: Page; snapshot: TradingSnapshot }) { if (page === "overview") return <Overview snapshot={snapshot} />; if (page === "strategies") return <Strategies snapshot={snapshot} />; if (page === "signals") return <Signals snapshot={snapshot} />; if (page === "positions") return <Positions snapshot={snapshot} />; if (page === "orders") return <Orders snapshot={snapshot} />; if (page === "risk") return <Risk snapshot={snapshot} />; if (page === "reviews") return <Deferred title="Reviews" message="Backend review API not exposed yet" source={{ status: "unavailable" }} />; if (page === "daily-review") return <Deferred title="Daily Review" message="Waiting for backend Daily Review API" source={snapshot.optional["/daily-reviews"] ?? { status: "loading" }} />; if (page === "learning") return <Deferred title="Learning" message="Learning backend not exposed yet" source={snapshot.optional["/learning"] ?? { status: "loading" }} />; return <System snapshot={snapshot} />; }

export default function App() {
  const [page, setPage] = useState<Page>(() => resolvePage(window.location.hash)); const { snapshot, refresh } = useTradingSnapshot();
  useEffect(() => { const update = () => setPage(resolvePage(window.location.hash)); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, []);
  const label = pages.find(([id]) => id === page)?.[1] ?? "Overview"; const offline = snapshot.health.status === "offline";
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">TC</span><div><strong>Trading Control</strong><small>PAPER · LOCAL</small></div></div><nav aria-label="Primary navigation">{pages.map(([id, name]) => <a key={id} href={`#/${id}`} aria-current={id === page ? "page" : undefined}>{name}</a>)}</nav><div className="sidebar-foot"><strong>NO EXECUTION AUTHORITY</strong><span>Backend remains the source of truth.</span></div></aside><main><header className="topbar"><div><p className="eyebrow">Local trading control center</p><h1>{label}</h1><p className="page-description">Real local backend data only. Missing endpoints and empty records remain visible as such.</p></div><div className="environment" aria-label="Environment: paper local"><strong>PAPER</strong><span>{offline ? "Backend Offline" : `WebSocket ${snapshot.websocket}`}</span></div></header>{offline && <section className="contract-notice"><div><p className="eyebrow">Backend Offline</p><h2>Local API is unavailable</h2><p>Expected API: {API_BASE_URL}. The UI will retry automatically and reconnect when the backend is available.</p></div><button type="button" onClick={() => void refresh()}>Retry now</button></section>}<Content page={page} snapshot={snapshot} /></main></div>;
}
